// sdk/js/orm/src/frontendAdapters/solid-js/useDiscrete.ts
// Copyright (c) 2026 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights diserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { useDeepSignal } from "@ng-org/alien-deepsignals/solid-js";
import { DiscreteOrmSubscription } from "../../connector/DiscreteOrmSubscription.ts";
import { DiscreteRoot } from "../../types.ts";
import { DeepSignal } from "@ng-org/alien-deepsignals";
import {
    Accessor,
    createEffect,
    createMemo,
    createResource,
    createSignal,
    onCleanup,
} from "solid-js";

/**
 * Hook to subscribe to an existing discrete (JSON) CRDT document.
 * You can modify the returned object like any other JSON object. Changes are immediately
 * reflected in the CRDT document.
 *
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the engine (or other components) cause an immediate rerender.
 *
 * In comparison to `useShape`, discrete CRDTs are untyped.
 * You can put any JSON data inside and need to validate the schema yourself.
 *
 * @param documentId The NURI of the CRDT document or and Accessor that eventually returns a string.
 * @returns An store-like object that contains as `data` the reactive DeepSignal object or undefined if available yet.
 *          As long as the accessor returns `undefined`, `subscription` is undefined too.
 *
 *@example
 * ```tsx
 * function Expenses() {
 *    // We assume you have created a CRDT document already, as below.
 *    // const documentId = await ng.doc_create(
 *    //     session_id,
 *    //     crdt, // "Automerge" | "YMap" | "YArray"
 *    //     crdt === "Automerge" ? "data:json" : crdt === "YMap ? "data:map" : "data:array",
 *    //     "store",
 *    //     undefined
 *    // );
 *    const dis = useDiscrete(documentId);
 *
 *    // If document is new / empty, we need to set up the basic structure.
 *    createEffect(() => {
 *        if (dis.doc && !dis.doc.expenses) {
 *            dis.doc.expenses = [];
 *        }
 *    });
 *
 *    const createExpense = () => {
 *        dis.doc?.expenses?.push({
 *            title: "New expense",
 *            date: new Date().toISOString(),
 *        });
 *    };
 *    return (
 *       <div>
 *          {!dis.doc.expenses &&
 *             <>Loading...</>
 *          }
 *          {dis.doc &&
 *             <Show when={dis.doc.expenses.length === 0}>
 *                 No expenses yet.
 *             </Show>
 *             <Show when={dis.doc.expenses.length > 0}>
 *                <button
 *                    onclick={() => createExpense()}
 *                >
 *                    + Add expense
 *                </button>
 *                <For each={dis.doc.expenses}>
 *                   {expense =>
 *                      <ExpenseCard
 *                         expense={expense}
 *                      />
 *                   }
 *                </For>
 *             </Show>
 *          }
 *       </div>
 *    );
 * }
 *
 * // If you modify expense in the component,
 * // the changes are immediately propagated to other consuming components
 * // And persisted in the database.
 * function ExpenseCard(props: {expense: DeepSignal<Expense>}) {
 *    const { expense } = defineProps<{
 *        expense: DeepSignal<Expense>;
 *    }>();
 *
 *    return (
 *       <input
 *          placeholder="Expense title"
 *          value={expense.title}
 *          onchange={e => { expense.title = e.target.value }}
 *       />
 *    );
 * }
 * ```
 */
export function useDiscrete<
    T extends object | Array<any> = DiscreteRoot,
    DOC_ID extends string | Accessor<string | undefined> =
        | string
        | Accessor<string | undefined>,
    DOC_ID_FLAT = DOC_ID extends Accessor<infer D> ? D : DOC_ID,
>(
    documentId: DOC_ID
): undefined extends DOC_ID_FLAT
    ? EmptyUseShapeResult<T> | UseShapeResult<T>
    : UseShapeResult<T> {
    const subscriptionSignal = createMemo(() => {
        let resolvedId: string;
        if (typeof documentId === "function") {
            const d = documentId();
            if (!d) return undefined;
            resolvedId = d;
        } else {
            resolvedId = documentId;
        }
        const subscription = DiscreteOrmSubscription.getOrCreate<T>(resolvedId);

        onCleanup(() => {
            subscription.close();
        });

        return subscription;
    });

    // Signal-ize (useDeepSignal-bound) data from subscriptions's readyPromise.
    const [dataSignal] = createResource(
        () => subscriptionSignal(),
        async (sub) => {
            // If we call useDeepSignal async, it won't be called inside
            // component initialization, so we pass a bound version.
            let onClean: undefined | (() => void) = undefined;
            let registerCleanup = (cb: () => void) => {
                onClean = cb;
            };
            onCleanup(() => {
                onClean?.();
            });

            return useDeepSignal((await sub.readyPromise) as T, {
                registerCleanup,
            });
        }
    );

    // isLoading getter (just to trigger)
    const [onIsLoadingGet, onIsLoadingSet] = createSignal(undefined, {
        equals: false,
    });
    createEffect(() => {
        subscriptionSignal()?.readyPromise.then(() => {
            onIsLoadingSet();
        });
    });

    // Construct promise.
    let resolveDataPromise: (p: any) => any;
    let rejectDataPromise: (p: any) => any;
    const dataPromise = new Promise((resolve, reject) => {
        resolveDataPromise = resolve;
        rejectDataPromise = reject;
    });
    createEffect(() => {
        subscriptionSignal()
            ?.readyPromise.then(resolveDataPromise)
            .catch(rejectDataPromise);
    });

    // @ts-ignore
    return {
        get doc() {
            return dataSignal();
        },
        get isLoading() {
            onIsLoadingGet();
            const sub = subscriptionSignal();
            return !sub?.isReady;
        },
        get subscription() {
            return subscriptionSignal() as any;
        },
        promise: dataPromise as any,
    };
}

type EmptyUseShapeResult<T = DiscreteRoot> = Omit<
    UseShapeResult<T>,
    "subscription"
> & {
    subscription: undefined;
    doc: undefined;
    isLoading: true;
};

type UseShapeResult<T = DiscreteRoot> = {
    /**
     * A promise that resolves once the data is loaded.
     * Note that if `conf` is `undefined`, this property is `undefined`.
     */
    promise: Promise<DeepSignal<T>>;
    /** The underlying {@link DiscreteOrmSubscription} through which the data is loaded. */
    subscription: DiscreteOrmSubscription<T>;
} & DATA_STATE<T>;

type DATA_STATE<T = DiscreteRoot> =
    | {
          /**
           * `true` when no data is available yet.
           *
           * It is *not* set to `true` while loading pages (through `nextPage()` or `previousPage()`.
           */
          isLoading: false;
          /**
           * The requested data, once loaded. While still loading, `data` wil be empty.
           *
           * Depending on your orderBy config, this will either be a {@link DeepSignalSet}
           * or a [`DeepSignal<ReadonlyArray>`]({@link DeepSignal}) (you can modify its properties and sub-objects though).
           *
           * This object is the value returned by {@link DiscreteOrmSubscription.signalObject}.
           */
          doc: T;
      }
    | {
          isLoading: true;
          doc: undefined;
      };

// sdk/js/orm/src/frontendAdapters/react/useDiscrete.ts
// Copyright (c) 2026 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { useEffect, useMemo, useRef } from "react";
import { DiscreteOrmSubscription } from "../../connector/discrete/discreteOrmSubscriptionHandler.ts";
import { useDeepSignal } from "@ng-org/alien-deepsignals/react";
import { DeepSignal } from "@ng-org/alien-deepsignals";
import { DiscreteRoot } from "../../types.ts";

const EMPTY_OBJECT = {} as const;

/**
 * Hook to subscribe to an existing discrete (JSON) CRDT document.
 * You can modify the returned object like any other JSON object. Changes are immediately
 * reflected in the CRDT document.
 *
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the engine (or other components) cause an immediate rerender.
 *
 * In comparison to {@link reactUseShape}, discrete CRDTs are untyped.
 * You can put any JSON data inside and need to validate the schema yourself.
 *
 * @param documentId The IRI of the CRDT document.
 * @returns An object that contains as `data` the reactive DeepSignal object or undefined if `documentId` is undefined.
 *
 * @example
 * ```tsx
 * // We assume you have created a CRDT document already, as below.
 * // const documentId = await ng.doc_create(
 * //     session_id,
 * //     crdt, // "Automerge" | "YMap" | "YArray". YArray is for root arrays, the other two have objects at root.
 * //     crdt === "Automerge" ? "data:json" : crdt === "YMap ? "data:map" : "data:array",
 * //     "store",
 * //     undefined
 * // );
 *
 * function Expenses({documentId}: {documentId: string}) {
 *     const { data } = useDiscrete(documentId);
 *
 *     // If the CRDT document is still empty, we need to initialize it.
 *     if (data && !data.expenses) {
 *         data.expenses = [];
 *     }
 *     const expenses = data?.expenses;
 *
 *     const createExpense = useCallback(() => {
 *             // Note that we use *expense["@id"]* as a key in the expense list.
 *             // Every object added to a CRDT array gets a stable `@id` property assigned
 *             // which you can use for referencing objects in arrays even as
 *             // objects are removed or added from the array.
 *             // The `@id` is an IRI with the schema `<documentId>:d:<object-specific id>`.
 *             // Since the `@id` is generated in the engine, the object is
 *             // *preliminarily given a mock id* which will be replaced immediately.
 *             expenses.push({
 *                 title: "New expense",
 *                 date: new Date().toISOString(),
 *             });
 *         },
 *         [expenses]
 *     );
 *
 *     // Still loading (data undefined)?
 *     if (!data) return <div>Loading...</div>;
 *
 *     return (
 *         <div>
 *             <button
 *                 onClick={() => createExpense()}
 *             >
 *                 + Add expense
 *             </button>
 *             <div>
 *                 {expenses.length === 0 ? (
 *                     <p>
 *                         No expenses yet.
 *                     </p>
 *                 ) : (
 *                     expenses.map((expense) => (
 *                         <ExpenseCard
 *                             key={expense["@id"]}
 *                             expense={expense}
 *                         />
 *                     ))
 *                 )}
 *             </div>
 *         </div>
 *     );
 * }
 * ```
 *
 * ---
 * In the ExpenseCard component:
 * ```tsx
 * function ExpenseCard({expense}: {expense: Expense}) {
 *    return (
 *        <input
 *            value={expense.title}
 *            onChange={(e) => {
 *                expense.title = e.target.value; // Changes trigger rerender.
 *            }}
 *        />
 *        <div>
 *            <p>Date</p>
 *            <p>{expense.data}
 *        </div
 *    );
 * }
 * ```
 */

export function useDiscrete<T extends DiscreteRoot = DiscreteRoot>(
    documentId: string | undefined
) {
    const prevDocumentId = useRef<string | undefined>(undefined);
    const prevOrmSubscription = useRef<DiscreteOrmSubscription | undefined>(
        undefined
    );

    const ormConnection = useMemo(() => {
        // Close previous connection if documentId changed.
        if (
            prevOrmSubscription.current &&
            prevDocumentId.current !== documentId
        ) {
            prevOrmSubscription.current.close();
            prevOrmSubscription.current = undefined;
        }

        // If no documentId, return undefined.
        if (!documentId) {
            prevDocumentId.current = undefined;
            return undefined;
        }

        // Create new connection only if needed.
        if (
            !prevOrmSubscription.current ||
            prevDocumentId.current !== documentId
        ) {
            prevOrmSubscription.current =
                DiscreteOrmSubscription.getOrCreate(documentId);
            prevDocumentId.current = documentId;
        }

        return prevOrmSubscription.current;
    }, [documentId]);

    useEffect(() => {
        return () => {
            prevOrmSubscription.current?.close();
        };
    }, []);

    // useDeepSignal requires an object, so pass empty object when no connection.
    const signalSource = ormConnection?.signalObject ?? EMPTY_OBJECT;
    const deepSignalValue = useDeepSignal(signalSource) as DeepSignal<T>;

    // Only return data if we have a valid connection with a signal object.
    const dataOrUndefined = ormConnection?.signalObject
        ? deepSignalValue
        : undefined;

    return { doc: dataOrUndefined };
}
