// sdk/js/orm/src/frontendAdapters/solid-js/useShape.ts
// Copyright (c) 2026 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { normalizeConf } from "../../types.ts";
import { useDeepSignal } from "@ng-org/alien-deepsignals/solid-js";
import {
    Accessor,
    createEffect,
    createMemo,
    createResource,
    createSignal,
    onCleanup,
} from "solid-js";
import type { BaseType, ShapeType } from "@ng-org/shex-orm";
import {
    RdfOrmSubscription,
    RdfOrmSubscriptionFor,
} from "../../connector/RdfOrmSubscription.ts";
import { DeepSignalSet, DeepSignal } from "@ng-org/alien-deepsignals";
import {
    RdfOrmConfig,
    SubscriptionData,
    WithMaybePagination,
} from "../../utilTypes.ts";

/**
 * Hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 * The returned objects are as easy to use as other TypeScript objects.
 *
 * Returns a {@link DeepSignalSet} of objects matching the shape and that are within the provided scope.
 * Establishes a 2-way binding: Modifications to the object are immediately committed,
 * changes coming from the backend (or other components) cause an immediate rerender.
 *
 * @param shapeType The {@link ShapeType} that the items should conform to (generated by the shex-orm tool).
 * @param conf The {@link RdfOrmConfig}, a graph string, or an Accessor to a config object or string.
 *
 *
 * @returns An store-like object which contains the data and utility properties.
 *          As long as the accessor returns `undefined`, the `subscription` property stays undefined.
 *
 * @example
 * ```tsx
 * export function Expenses() {
 *   // Contains all expense objects with `@id` <s1 IRI> or <s2 IRI> and `@graph` <g1 NURI> or <g2 NURI>
 *   const expenses = useShape(ExpenseShapeType,
 *        { graphs: ["<g1 NURI>", "<g2 NURI>"],
 *          subjects: ["<s1 IRI>", "<s2 IRI>"]});
 *
 *   const addExpense = () => {
 *        // Once expenses.data is loaded, you can add new items.
 *        // Leave `@id` empty and a new one is auto-generated.
 *        expenses.data?.add({"@graph": "<g1 or g2 NURI>", "@id": "", title: "Example title"});
 *   };
 *
 *   return (
 *      <Switch>
 *          <Match when={expenses.isLoading}>
 *              <p>
 *                  Loading...
 *              </p>
 *          </Match>
 *          <Match when={expenses.data.size === 0}>
 *              <p>
 *                  No expenses yet.
 *              </p>
 *          </Match>
 *          <Match>
 *              <For each={[...expenses.data]}>
 *                  {(expense) =>
 *                      <ExpenseCard
 *                          expense={expense}
 *                      />
 *                  }
 *              </For>
 *              <button onclick={addExpense}>
 *                  Add Expense
 *              </button>
 *          </Match>
 *      </Switch>
 *    );
 * }
 *
 * // If you modify expense in the component,
 * // the changes are immediately propagated to other consuming components.
 * // And persisted in the database.
 * function ExpenseCard(props: {expense: DeepSignal<Expense>}) {
 *     return (
 *       <input
 *          placeholder="Expense title"
 *          value={props.expense.title}
 *          onchange={e => props.expense.title = e.target.value}
 *       />
 * }
 *
 * ```
 */
const useShape = <
    ST extends ShapeType<T>,
    CONF_OR_ACCESSOR extends
        | RdfOrmConfig<T>
        | string
        | Accessor<undefined | RdfOrmConfig<T> | string>,
    T extends BaseType = ST extends ShapeType<infer T_> ? T_ : never,
    CONF_OR_BASIC = CONF_OR_ACCESSOR extends Accessor<infer C>
        ? C
        : CONF_OR_ACCESSOR,
    CONF_OR_BASIC_NO_UNDEFINED = Exclude<CONF_OR_BASIC, undefined>,
    CONF extends
        RdfOrmConfig<T> = CONF_OR_BASIC_NO_UNDEFINED extends RdfOrmConfig<T>
        ? CONF_OR_BASIC_NO_UNDEFINED
        : RdfOrmConfig<T>,
>(
    shape: ST,
    conf: CONF_OR_ACCESSOR
): undefined extends CONF_OR_BASIC
    ?
          | EmptyUseShapeResult<ST, CONF, T>
          | UseShapeResult<ST, Exclude<CONF, undefined>, T>
    : UseShapeResult<ST, CONF, T> => {
    const normalizedConf = createMemo(() => {
        if (typeof conf === "function") {
            const confOrUndefined = conf();
            return confOrUndefined && normalizeConf(confOrUndefined);
        } else {
            return normalizeConf(conf);
        }
    });

    const subscriptionSignal = createMemo(() => {
        const c = normalizedConf();
        if (!c) return undefined;

        const sub = RdfOrmSubscription.getOrCreate(shape, c);

        onCleanup(() => {
            sub.close();
        });

        return sub;
    });

    const [dataSignal] = createResource(
        () => subscriptionSignal(),
        async (sub) => {
            // If we call useDeepSignal async, it won't be called inside
            // component initialization, so we pass a bound version.
            let onClean: undefined | (() => void) = undefined;
            let registerCleanup = (cb: () => void) => {
                onClean = cb;
            };
            onCleanup(() => {
                onClean?.();
            });

            return useDeepSignal(await sub.readyPromise, {
                registerCleanup,
            });
        }
    );
    const [onIsLoadingGet, onIsLoadingSet] = createSignal(undefined, {
        equals: false,
    });

    createEffect(() => {
        subscriptionSignal()?.readyPromise.then(() => {
            onIsLoadingSet();
        });
    });

    let resolveDataPromise: (p: any) => any;
    let rejectDataPromise: (p: any) => any;
    const dataPromise = new Promise((resolve, reject) => {
        resolveDataPromise = resolve;
        rejectDataPromise = reject;
    });
    createEffect(() => {
        subscriptionSignal()
            ?.readyPromise.then(resolveDataPromise)
            .catch(rejectDataPromise);
    });

    // @ts-ignore
    return {
        get data() {
            return dataSignal();
        },
        get isLoading() {
            onIsLoadingGet();
            const sub = subscriptionSignal();
            return !sub?.isReady;
        },
        get nextPage() {
            return () => {
                // @ts-ignore
                subscriptionSignal()?.nextPage();
            };
        },
        get previousPage() {
            return () => {
                // @ts-ignore
                subscriptionSignal()?.previousPage();
            };
        },
        get subscription() {
            return subscriptionSignal() as any;
        },
        promise: dataPromise as any,
    };
};

type EmptyUseShapeResult<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
> = Omit<UseShapeResult<ST, CONF, T>, "subscription"> & {
    subscription: undefined;
    data: undefined;
    isLoading: true;
};

export default useShape;

export type UseShapeResult<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
> = WithMaybePagination<{}, CONF, T> & {
    /**
     * A promise that resolves once the data is loaded.
     * Note that if `conf` is `undefined`, this property is `undefined`.
     */
    promise: Promise<SUBSCRIPTION_DATA>;
    /**
     * The underlying {@link RdfOrmSubscription} through which the data is loaded. \
     */
    subscription: RdfOrmSubscriptionFor<ST, CONF, T>;
} &
    /**
     * Utility type to represent the possible states of data loading.
     *
     */
    DATA_STATE<CONF, T>;

type DATA_STATE<
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
> =
    | {
          /**
           * `true` when no data is available yet.
           *
           * It is *not* set to `true` while loading pages (through `nextPage()` or `previousPage()`.
           */
          isLoading: false;
          /**
           * The requested data, once loaded. While still loading, `data` wil be empty.
           *
           * Depending on your orderBy config, this will either be a {@link DeepSignalSet}
           * or a [`DeepSignal<ReadonlyArray>`]({@link DeepSignal}) (you can modify its properties and sub-objects though).
           *
           * This object is the value returned by {@link RdfOrmSubscription.signalObject}.
           */
          data: SUBSCRIPTION_DATA;
      }
    | {
          isLoading: true;
          data: undefined;
      };

// sdk/js/orm/src/frontendAdapters/react/useShape.ts
// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import type { BaseType } from "@ng-org/shex-orm";
import { useDeepSignal } from "@ng-org/alien-deepsignals/react";
import type { ShapeType } from "@ng-org/shex-orm";
import { useEffect, useMemo, useRef, useState } from "react";
import { normalizeConf } from "../../types.ts";
import {
    RdfOrmSubscription,
    RdfOrmSubscriptionFor,
} from "../../connector/RdfOrmSubscription.ts";
import type { DeepSignalSet, DeepSignal } from "@ng-org/alien-deepsignals";
import {
    WithMaybePagination,
    RdfOrmConfig,
    SubscriptionData,
} from "../../utilTypes.ts";

const EMPTY_OBJECT = {} as const;

/**
 * Hook to subscribe to RDF data in the graph database using a shape, see {@link ShapeType}.
 *
 * Establishes a 2-way binding with the returned data: Modifications to the data are automatically committed,
 * changes coming from the engine (or other components) cause an immediate rerender.
 *
 * @param shapeType The {@link ShapeType} that the items should conform to (generated by the shex-orm tool).
 * @param conf The config that can be a document nuri, {@link RdfOrmConfig} or undefined.
 * @returns A {@link UseShapeResult} with the orm objects or an empty set, if still loading.\
 *          If the conf is explicitly set to `undefined`, the returned data is `undefined` and `isLoading` is false.
 *
 * @example
 * ```tsx
 * function Expenses() {
 *     const { data: expenses, isLoading }: DeepSignal<Set<Expense>> = useShape(
 *         ExpenseShapeType,
 *         {
 *             graphs: ["<document NURI>"]
 *             orderBy: {dateOrPurchase: "desc"}
 *         }
 *     );
 *
 *     const createExpense = useCallback(
 *         () => {
 *             expenses.add({
 *                 "@graph": `<document NURI>`,
 *                 "@type": "did:ng:z:Expense",
 *                 "@id": "", // Assigns ID automatically, if set to "".
 *                 title: "New expense",
 *                 dateOfPurchase: obj.dateOfPurchase ?? new Date().toISOString(),
 *             });
 *         },
 *         [expenses]
 *     );
 *
 *     return (
 *         <div>
 *             <button
 *                 onClick={() => createExpense({})}
 *             >
 *                 + Add expense
 *             </button>
 *             <div>
 *                 {isLoading && (
 *                     <p>
 *                         Loading...
 *                     </p>
 *                 )}
 *                 {expenses && expenses.size === 0 && (
 *                     <p>
 *                         No expenses yet.
 *                     </p>
 *                 )}
 *                 {expenses && expenses.size > 0 && (
 *                     [...expenses].map((expense) => (
 *                         // You can modify the expense's properties in the ExpenseCard component
 *                         // which will instantly trigger a rerender.
 *                         <ExpenseCard
 *                             key={expense["@id"]}
 *                             expense={expense}
 *                         />
 *                     ))
 *                 )}
 *             </div>
 *         </div>
 *     );
 * }
 * ```
 */
const useShape = <
    ST extends ShapeType<T>,
    const CONF extends RdfOrmConfig<T>,
    T extends BaseType = ST extends ShapeType<infer T_> ? T_ : never,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
>(
    shapeType: ST,
    conf: CONF | string | undefined
): UseShapeResult<ST, CONF, T> => {
    const dependencies = [
        typeof conf,
        JSON.stringify((conf as CONF)?.graphs),
        JSON.stringify((conf as CONF)?.subjects),
        (conf as CONF)?.maxActivePages,
        (conf as CONF)?.pageSize,
        JSON.stringify((conf as CONF)?.orderBy),
    ];
    const parsedConf = useMemo(
        () => (!conf ? undefined : normalizeConf(conf)),
        dependencies
    );
    const [isReady, setIsReady] = useState(false);

    const ormSubscription = useMemo(() => {
        if (parsedConf === undefined) return undefined;

        const newOrmSubscription = RdfOrmSubscription.getOrCreate(
            shapeType,
            parsedConf
        );

        return newOrmSubscription;
    }, dependencies);

    useEffect(() => {
        if (!ormSubscription) return;

        ormSubscription?.readyPromise.then(() => {
            setIsReady(true);
        });

        return () => {
            setIsReady(false);
            ormSubscription.close();
        };
    }, [ormSubscription]);

    // If no data has arrived or the scope is unset, use a dummy object
    // that won't be returned (useDeepSignal requires some kind of data).
    const state = useDeepSignal(
        ormSubscription && isReady
            ? ormSubscription.signalObject
            : EMPTY_OBJECT,
        {
            replaceProxiesInBranchOnChange: true,
        }
    );

    const nextPage =
        ormSubscription?.mode === "orderedPaginatedCumulative" ||
        ormSubscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              ormSubscription.nextPage
            : undefined;
    const previousPage =
        ormSubscription?.mode === "orderedPaginatedSimple"
            ? // @ts-ignore
              ormSubscription.previousPage
            : undefined;

    // @ts-ignore
    return {
        data: (isReady ? state : undefined) as SUBSCRIPTION_DATA,
        isLoading: !ormSubscription ? false : ormSubscription.isReady,
        promise: ormSubscription?.readyPromise,
        subscription: ormSubscription,
        nextPage,
        previousPage,
    };
};

export default useShape;

type UseShapeResult_<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
    SUBSCRIPTION_DATA = SubscriptionData<T, CONF>,
> = {
    /**
     * Initializes loading of the next page.
     * This will update the data but you will not be called back on it.
     */
    nextPage: () => void;
    /**
     * Initializes loading of the previous page.
     * This will update the data but you will not be called back on it.
     */
    previousPage: () => void;
    /**
     * `true` when no data is available yet and `conf` is not `undefined`.
     *
     * It is *not* set to `true` while loading pages (through `nextPage()` or `previousPage()`.
     */
    isLoading: boolean;
    /**
     * The requested data, once loaded.
     * Depending on your orderBy config, this will either be a {@link DeepSignalSet}
     * or a [`DeepSignal<ReadOnlyArray>`]({@link DeepSignal}) (you can modify its properties and sub-objects though).
     *
     * This object is the value returned by {@link RdfOrmSubscription.signalObject} with the following exception:
     * To capture modifications to it in react, the root is a proxy that is replaced on every relevant rerender.
     */
    data: SUBSCRIPTION_DATA | undefined;
    /**
     * A promise that resolves once the data is loaded.
     * Note that if `conf` is `undefined`, this property is `undefined`.
     */
    promise: CONF extends undefined ? undefined : Promise<SUBSCRIPTION_DATA>;
    /** The underlying {@link RdfOrmSubscription} through which the data is loaded. */
    subscription: CONF extends undefined
        ? undefined
        : RdfOrmSubscriptionFor<ST, CONF, T>;
};

export type UseShapeResult<
    ST extends ShapeType<any>,
    CONF extends RdfOrmConfig<T>,
    T extends BaseType,
> = WithMaybePagination<UseShapeResult_<ST, CONF, T>, CONF, T>;
