// sdk/js/examples/expense-tracker-rdf/src/frontends/svelte/Expenses.svelte
<!--
Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
All rights reserved.
Licensed under the Apache License, Version 2.0
<LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
at your option. All files in the project carrying such
notice may not be copied, modified, or distributed except
according to those terms.
SPDX-License-Identifier: Apache-2.0 OR MIT
-->
<script lang="ts">
  import { useShape } from "@ng-org/orm/svelte";
  import {
    ExpenseCategoryShapeType,
    ExpenseShapeType,
  } from "../../shapes/orm/expenseShapes.shapeTypes";
  import type { Expense } from "../../shapes/orm/expenseShapes.typings";
  import { sessionPromise, session } from "../../utils/ngSession";
  import ExpenseCard from "./ExpenseCard.svelte";
  import { insertObject } from "@ng-org/orm";

  const privateNuri = session && `did:ng:${session?.private_store_id}`;
  const expenses = useShape(
    ExpenseShapeType,
    privateNuri && {
      graphs: privateNuri,
      orderBy: { dateOfPurchase: "desc" },
      pageSize: 4,
      maxActivePages: 1,
    }
  );
  const categories = useShape(ExpenseCategoryShapeType, privateNuri);

  async function createExpense(obj: Partial<Expense> = {}) {
    const session = await sessionPromise;

    insertObject(ExpenseShapeType, {
      "@graph": `did:ng:${session.private_store_id}`,
      "@type": "did:ng:z:Expense",
      "@id": "",
      amount: obj.amount ?? 1,
      recurrenceInterval: obj.recurrenceInterval ?? "",
      description: obj.description ?? undefined,
      totalPrice: obj.totalPrice ?? 0,
      paymentStatus: obj.paymentStatus ?? "did:ng:z:Paid",
      isRecurring: obj.isRecurring ?? false,
      expenseCategory: obj.expenseCategory ?? new Set<string>(),
      dateOfPurchase: obj.dateOfPurchase ?? new Date().toISOString(),
      title: obj.title ?? "New Expense",
    });
  }
</script>

<section class="panel">
  <header class="panel-header">
    <div>
      <p class="label-accent">Expenses</p>
      <h2 class="title">Recent activity</h2>
    </div>
    <button class="primary-btn" onclick={() => createExpense({})}>
      + Add expense
    </button>
  </header>
  <div class="cards-stack">
    {#if !expenses.data || !categories.data}
      <p class="muted">Loading...</p>
    {:else if expenses.data.length === 0}
      <p class="muted">
        Nothing tracked yet - log your first purchase to kick things off.
      </p>
    {:else}
      {#each expenses.data as expense, index (expense["@id"])}
        <ExpenseCard
          expense={expenses.data[index]}
          availableCategories={categories.data}
        />
      {/each}
    {/if}
  </div>
  <div class="pagination-bar">
    <button type="button" class="primary-btn" onClick={() => previousPage()}>
      {"<"} previous page
    </button>
    <button type="button" class="primary-btn" onClick={() => nextPage()}>
      next page {">"}
    </button>
  </div>
</section>

// sdk/js/examples/expense-tracker-rdf/src/frontends/react/Expenses.tsx
// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { useCallback } from "react";
import { useShape } from "@ng-org/orm/react";
import {
    ExpenseCategoryShapeType,
    ExpenseShapeType,
} from "../../shapes/orm/expenseShapes.shapeTypes";
import type { Expense } from "../../shapes/orm/expenseShapes.typings";
import { sessionPromise, session } from "../../utils/ngSession";
import { ExpenseCard } from "./ExpenseCard";
import { insertObject } from "@ng-org/orm";

export function Expenses() {
    const privateNuri = session && `did:ng:${session?.private_store_id}`;
    const {data: expenses , nextPage, previousPage} = useShape(ExpenseShapeType, session && {
        graphs: [privateNuri!],
        orderBy: {dateOfPurchase: "desc"},
        maxActivePages: 1,
        pageSize: 4
    });
    const {data: expenseCategories } = useShape(ExpenseCategoryShapeType, privateNuri );
    const createExpense = useCallback(
        async (obj: Partial<Expense> = {}) => {
            const session = await sessionPromise;

            insertObject(ExpenseShapeType,{
                "@graph": `did:ng:${session.private_store_id}`,
                "@type": "did:ng:z:Expense",
                "@id": "",
                amount: obj.amount ?? 1,
                description: obj.description ?? "",
                totalPrice: obj.totalPrice ?? 0,
                paymentStatus: obj.paymentStatus ?? "did:ng:z:Paid",
                isRecurring: obj.isRecurring ?? false,
                expenseCategory: obj.expenseCategory ?? new Set<string>(),
                dateOfPurchase: obj.dateOfPurchase ?? new Date().toISOString(),
                title: obj.title ?? "New expense",
                recurrenceInterval: obj.recurrenceInterval ?? "",
            });
        },
        []
    );

    return (
        <section className="panel">
            <header className="panel-header">
                <div>
                    <p className="label-accent">Expenses</p>
                    <h2 className="title">Recent activity</h2>
                </div>
                <button
                    type="button"
                    className="primary-btn"
                    onClick={() => createExpense({})}
                >
                    + Add expense
                </button>

            </header>
            <div className="cards-stack">
                {!expenses && (
                    <p className="muted">
                        Loading...
                    </p>
                )}
                {(expenses && expenses.length === 0) && (
                    <p className="muted">
                        Nothing tracked yet - log your first purchase to kick
                        things off.
                    </p>
                )}
                {expenses && expenses.length > 0 && (
                    expenses.map((expense) => (
                        <ExpenseCard
                            key={expense['@id']}
                            expense={expense}
                            availableCategories={expenseCategories}
                        />
                    ))
                )}
            </div>
            <div className="pagination-bar">
                <button
                    type="button"
                    className="primary-btn"
                    onClick={() => previousPage()}
                >
                    {"<"} previous page
                </button>
                <button
                    type="button"
                    className="primary-btn"
                    onClick={() => nextPage()}
                >
                    next page {">"}
                </button>

            </div>
        </section>
    );
}
