// sdk/js/examples/expense-tracker-rdf/src/frontends/vue/ExpenseCard.vue
<!--
Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
All rights reserved.
Licensed under the Apache License, Version 2.0
<LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
at your option. All files in the project carrying such
notice may not be copied, modified, or distributed except
according to those terms.
SPDX-License-Identifier: Apache-2.0 OR MIT
-->
<script setup lang="ts">
import { computed, ref } from "vue";
import type {
    Expense,
    ExpenseCategory,
} from "../../shapes/orm/expenseShapes.typings";
import type { DeepSignal } from "@ng-org/orm";

const props = defineProps<{
    expense: DeepSignal<Expense>;
    availableCategories: DeepSignal<Set<ExpenseCategory>>;
}>();

const expense = props.expense;

const isEditing = ref(false);
const paymentStatusLabels: Record<Expense["paymentStatus"], string> = {
    "http://example.org/Paid": "Paid",
    "http://example.org/Pending": "Pending",
    "http://example.org/Overdue": "Overdue",
    "http://example.org/Refunded": "Refunded",
};

const paymentStatusEntries = Object.entries(paymentStatusLabels);

const currencyFormatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 2,
});

const purchaseDate = computed(() =>
    expense.dateOfPurchase
        ? new Date(expense.dateOfPurchase).toLocaleDateString()
        : "Date not set"
);

const totalPriceDisplay = computed(() =>
    currencyFormatter.format(expense.totalPrice)
);

const isCategorySelected = (category: ExpenseCategory) =>
    !!expense.expenseCategory?.has(category["@id"]);

const toggleCategory = (category: ExpenseCategory, checked: boolean) => {
    if (checked) {
        if (!expense.expenseCategory) {
            expense.expenseCategory = new Set([
                category["@id"],
            ]) as DeepSignalSet<string>;
        } else {
            expense.expenseCategory.add(category["@id"]);
        }
    } else {
        expense.expenseCategory?.delete(category["@id"]);
    }
};

function nameOfCategory(categoryIri: string) {
    return props.availableCategories.find((c) => c["@id"] === categoryIri)
        ?.categoryName;
}

function categoryKey(category: ExpenseCategory) {
    return `${category["@graph"]}|${category["@id"]}`;
}
</script>

<template>
    <article class="expense-card">
        <div class="expense-header">
            <div class="header-text">
                <input
                    v-if="isEditing"
                    class="header-input"
                    v-model="expense.title"
                    placeholder="Expense title"
                />
                <h3 v-else class="header-title">
                    {{ expense.title || "New expense" }}
                </h3>
                <p class="muted small-margin">
                    {{ purchaseDate }}
                </p>
            </div>
            <button
                type="button"
                class="icon-btn"
                :aria-label="isEditing ? 'Close editing' : 'Edit expense'"
                @click="isEditing = !isEditing"
            >
                <svg
                    v-if="isEditing"
                    data-slot="icon"
                    fill="none"
                    stroke-width="1.5"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M6 18 18 6M6 6l12 12"
                    ></path>
                </svg>

                <svg
                    v-else
                    data-slot="icon"
                    fill="none"
                    stroke-width="1.5"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125"
                    ></path>
                </svg>
            </button>
        </div>
        <div class="info-grid">
            <div class="field-group">
                <span class="field-label">Description</span>
                <textarea
                    v-if="isEditing"
                    class="textarea"
                    v-model="expense.description"
                    placeholder="Add helpful context"
                ></textarea>
                <p v-else class="value-text">
                    {{ expense.description || "No description yet." }}
                </p>
            </div>
            <div class="field-group">
                <span class="field-label">Total price (€)</span>
                <input
                    v-if="isEditing"
                    type="number"
                    class="input"
                    v-model="expense.totalPrice"
                />
                <span v-else class="value-text">{{ totalPriceDisplay }}</span>
            </div>
            <div class="field-group">
                <span class="field-label">Quantity</span>
                <input
                    v-if="isEditing"
                    type="number"
                    min="1"
                    class="input"
                    v-model="expense.amount"
                />
                <span v-else class="value-text">{{ expense.amount ?? 1 }}</span>
            </div>
            <div class="field-group">
                <span class="field-label">Payment status</span>
                <select
                    v-if="isEditing"
                    class="select"
                    v-model="expense.paymentStatus"
                >
                    <option
                        v-for="[statusIri, label] in paymentStatusEntries"
                        :key="statusIri"
                        :value="statusIri"
                    >
                        {{ label }}
                    </option>
                </select>
                <span v-else class="value-text">
                    {{
                        paymentStatusLabels[expense.paymentStatus] ?? "Unknown"
                    }}
                </span>
            </div>
        </div>
        <div class="field-group">
            <span class="field-label">Categories</span>
            <template v-if="isEditing">
                <div
                    v-if="props.availableCategories.size"
                    class="category-picker"
                >
                    <label
                        v-for="category in props.availableCategories"
                        :key="categoryKey(category)"
                        class="category-option"
                    >
                        <input
                            type="checkbox"
                            class="checkbox"
                            :checked="isCategorySelected(category)"
                            @change="
                                (e) =>
                                    toggleCategory(
                                        category,
                                        (e.target as HTMLInputElement).checked
                                    )
                            "
                        />
                        <span class="category-text">
                            <strong>
                                {{ category.categoryName || "Unnamed" }}
                            </strong>
                            <small class="muted">
                                {{ category.description || "No description" }}
                            </small>
                        </span>
                    </label>
                </div>
                <p v-else class="muted">
                    No categories available yet. Create one in the panel above.
                </p>
            </template>
            <template v-else>
                <div v-if="expense.expenseCategory?.size" class="chip-list">
                    <span
                        v-for="category in expense.expenseCategory"
                        :key="category"
                        class="chip"
                    >
                        {{ nameOfCategory(category) || "Unnamed" }}
                    </span>
                </div>
                <p v-else class="muted">No categories linked.</p>
                <small class="helper-text">
                    Enter edit mode to link categories.
                </small>
            </template>
        </div>
    </article>
</template>

// sdk/js/examples/expense-tracker-rdf/src/frontends/react/ExpenseCard.tsx
// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { useState } from "react";
import type {
    Expense,
    ExpenseCategory,
} from "../../shapes/orm/expenseShapes.typings";
import type { DeepSignalSet } from "@ng-org/alien-deepsignals";

const paymentStatusLabels: Record<Expense["paymentStatus"], string> = {
    "http://example.org/Paid": "Paid",
    "http://example.org/Pending": "Pending",
    "http://example.org/Overdue": "Overdue",
    "http://example.org/Refunded": "Refunded",
};

const currencyFormatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 2,
});

export function ExpenseCard({
    expense,
    availableCategories,
}: {
    expense: Expense;
    availableCategories: DeepSignalSet<ExpenseCategory>;
}) {
    const [isEditing, setIsEditing] = useState(false);

    const purchaseDate = expense.dateOfPurchase
        ? new Date(expense.dateOfPurchase).toLocaleDateString()
        : "Date not set";
    const totalPriceDisplay = currencyFormatter.format(expense.totalPrice ?? 0);

    const categoryKey = (category: ExpenseCategory) =>
        `${category["@graph"]}|${category["@id"]}`;

    const isCategorySelected = (category: ExpenseCategory) =>
        !!expense.expenseCategory?.has(category["@id"]);

    const toggleCategory = (category: ExpenseCategory, checked: boolean) => {
        if (checked) {
            if (!expense.expenseCategory) {
                expense.expenseCategory = new Set([category["@id"]]);
            } else {
                expense.expenseCategory.add(category["@id"]);
            }
        } else {
            expense.expenseCategory?.delete(category["@id"]);
        }
    };

    const nameOfCategory = (categoryIri: string) =>
        [...availableCategories].find((c) => c["@id"] === categoryIri)
            ?.categoryName || "Unnamed";

    return (
        <article className="expense-card">
            <div className="expense-header">
                <div className="header-text">
                    {isEditing ? (
                        <input
                            className="header-input"
                            value={expense.title ?? ""}
                            placeholder="Expense title"
                            onChange={(e) => {
                                expense.title = e.target.value;
                            }}
                        />
                    ) : (
                        <h3 className="header-title">
                            {expense.title || "New expense"}
                        </h3>
                    )}
                    <p className="muted small-margin">{purchaseDate}</p>
                </div>
                <button
                    type="button"
                    className="icon-btn"
                    aria-label={isEditing ? "Close editing" : "Edit expense"}
                    onClick={() => setIsEditing((prev) => !prev)}
                >
                    {isEditing ? (
                        <svg data-slot="icon" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"></path>
                        </svg>
                    ) : (
                        <svg data-slot="icon" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125"></path>
                        </svg>
                    )}
                </button>
            </div>
            <div className="info-grid">
                <div className="field-group">
                    <span className="field-label">Description</span>
                    {isEditing ? (
                        <textarea
                            className="textarea"
                            value={expense.description ?? ""}
                            placeholder="Add helpful context"
                            onChange={(e) =>
                                (expense.description = e.target.value)
                            }
                        />
                    ) : (
                        <p className="value-text">
                            {expense.description || "No description yet."}
                        </p>
                    )}
                </div>
                <div className="field-group">
                    <span className="field-label">Total price (€)</span>
                    {isEditing ? (
                        <input
                            type="number"
                            className="input"
                            value={expense.totalPrice ?? 0}
                            onChange={(e) =>
                                (expense.totalPrice = Number(e.target.value))
                            }
                        />
                    ) : (
                        <span className="value-text">{totalPriceDisplay}</span>
                    )}
                </div>
                <div className="field-group">
                    <span className="field-label">Quantity</span>
                    {isEditing ? (
                        <input
                            type="number"
                            min={1}
                            className="input"
                            value={expense.amount ?? 1}
                            onChange={(e) =>
                                (expense.amount = Number(e.target.value))
                            }
                        />
                    ) : (
                        <span className="value-text">
                            {expense.amount ?? 1}
                        </span>
                    )}
                </div>
                <div className="field-group">
                    <span className="field-label">Payment status</span>
                    {isEditing ? (
                        <select
                            className="select"
                            value={expense.paymentStatus}
                            onChange={(e) =>
                                (expense.paymentStatus = e.target
                                    .value as Expense["paymentStatus"])
                            }
                        >
                            {Object.entries(paymentStatusLabels).map(
                                ([paymentStatusIri, label]) => (
                                    <option
                                        value={paymentStatusIri}
                                        key={paymentStatusIri}
                                    >
                                        {label}
                                    </option>
                                )
                            )}
                        </select>
                    ) : (
                        <span className="value-text">
                            {paymentStatusLabels[expense.paymentStatus] ??
                                "Unknown"}
                        </span>
                    )}
                </div>
            </div>
            <div className="field-group">
                <span className="field-label">Categories</span>
                {isEditing ? (
                    availableCategories.size ? (
                        <div className="category-picker">
                            {[...availableCategories].map((category) => (
                                <label
                                    className="category-option"
                                    key={categoryKey(category)}
                                >
                                    <input
                                        type="checkbox"
                                        className="checkbox"
                                        checked={isCategorySelected(category)}
                                        onChange={(e) =>
                                            toggleCategory(
                                                category,
                                                e.target.checked
                                            )
                                        }
                                    />
                                    <span className="category-text">
                                        <strong>
                                            {category.categoryName || "Unnamed"}
                                        </strong>
                                        <small className="muted">
                                            {category.description ||
                                                "No description"}
                                        </small>
                                    </span>
                                </label>
                            ))}
                        </div>
                    ) : (
                        <p className="muted">
                            No categories available yet. Create one in the panel
                            above.
                        </p>
                    )
                ) : expense.expenseCategory?.size ? (
                    <div className="chip-list">
                        {[...expense.expenseCategory].map((categoryIri) => (
                            <span className="chip" key={categoryIri}>
                                {nameOfCategory(categoryIri)}
                            </span>
                        ))}
                    </div>
                ) : (
                    <p className="muted">No categories linked.</p>
                )}
                {!isEditing && (
                    <small className="helper-text">
                        Enter edit mode to link categories.
                    </small>
                )}
            </div>
        </article>
    );
}
