// sdk/js/examples/expense-tracker-discrete/src/frontends/svelte4/ExpenseCard.svelte
<!--
// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT
-->
<script lang="ts">
  import type { Expense, ExpenseCategory } from "../../types";

  export let expense: Expense;
  export let availableCategories: ExpenseCategory[] = [];

  let isEditing = false;

  const paymentStatusLabels: Record<Expense["paymentStatus"], string> = {
    Paid: "Paid",
    Pending: "Pending",
    Overdue: "Overdue",
    Refunded: "Refunded",
  };
  const paymentStatusEntries = Object.entries(paymentStatusLabels);

  const currencyFormatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 2,
  });

  $: purchaseDate =
    expense?.dateOfPurchase
      ? new Date(expense.dateOfPurchase).toLocaleDateString()
      : "Date not set";

  $: totalPriceDisplay = currencyFormatter.format(expense?.totalPrice ?? 0);

  const isCategorySelected = (category: ExpenseCategory) =>
    !!expense.expenseCategories?.includes(category["@id"] ?? "");

  const toggleCategory = (category: ExpenseCategory, checked: boolean) => {
    const categoryId = category["@id"];
    if (!categoryId) return;

    if (checked) {
      if (!expense.expenseCategories) {
        expense.expenseCategories = [categoryId];
      } else if (!expense.expenseCategories.includes(categoryId)) {
        expense.expenseCategories.push(categoryId);
      }
    } else {
      expense.expenseCategories = (expense.expenseCategories ?? []).filter(
        (value) => value !== categoryId
      );
    }
  }

  function nameOfCategory(categoryIri: string) {
    return availableCategories.find((c) => c["@id"] === categoryIri)
      ?.categoryName;
  }
</script>

<article class="expense-card">
  <div class="expense-header">
    <div class="header-text">
      {#if isEditing}
        <input
          class="header-input"
          value={expense.title ?? ""}
          oninput={(event) =>
            (expense.title = event.currentTarget?.value ?? "")}
          placeholder="Expense title"
        />
      {:else}
        <h3 class="header-title">{expense.title || "New expense"}</h3>
      {/if}
      <p class="muted small-margin">{purchaseDate}</p>
    </div>
    <button
      type="button"
      class="icon-btn"
      aria-label={isEditing ? "Close editing" : "Edit expense"}
      onclick={() => (isEditing = !isEditing)}
    >
      {#if isEditing }
        <svg data-slot="icon" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"></path>
        </svg>
      {:else}
        <svg data-slot="icon" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125"></path>
        </svg>
      {/if}
    </button>
  </div>
  <div class="info-grid">
    <div class="field-group">
      <span class="field-label">Description</span>
      {#if isEditing}
        <textarea
          class="textarea"
          value={expense.description ?? ""}
          oninput={(event) =>
            (expense.description = event.currentTarget?.value ?? "")}
          placeholder="Add helpful context"
        ></textarea>
      {:else}
        <p class="value-text">{expense.description || "No description yet."}</p>
      {/if}
    </div>
    <div class="field-group">
      <span class="field-label">Total price (€)</span>
      {#if isEditing}
        <input
          type="number"
          class="input"
          value={expense.totalPrice ?? 0}
          oninput={(event) => {
            const next = event.currentTarget?.valueAsNumber;
            expense.totalPrice = Number.isFinite(next) ? (next ?? 0) : 0;
          }}
        />
      {:else}
        <span class="value-text">{totalPriceDisplay}</span>
      {/if}
    </div>
    <div class="field-group">
      <span class="field-label">Quantity</span>
      {#if isEditing}
        <input
          type="number"
          min="1"
          class="input"
          value={expense.amount ?? 1}
          oninput={(event) => {
            const next = event.currentTarget?.valueAsNumber;
            expense.amount = Number.isFinite(next) ? (next ?? 1) : 1;
          }}
        />
      {:else}
        <span class="value-text">{expense.amount ?? 1}</span>
      {/if}
    </div>
    <div class="field-group">
      <span class="field-label">Payment status</span>
      {#if isEditing}
        <select
          class="select"
          value={expense.paymentStatus}
          onchange={(event) => {
            const selected = event.currentTarget?.value;
            if (selected) {
              expense.paymentStatus = selected as Expense["paymentStatus"];
            }
          }}
        >
          {#each paymentStatusEntries as [iri, label]}
            <option value={iri}>{label}</option>
          {/each}
        </select>
      {:else}
        <span class="value-text">
          {paymentStatusLabels[expense.paymentStatus] ?? "Unknown"}
        </span>
      {/if}
    </div>
  </div>
  <div class="field-group">
    <span class="field-label">Categories</span>
    {#if isEditing}
      {#if availableCategories.length}
        <div class="category-picker">
          {#each availableCategories as category}
            <label class="category-option">
              <input
                type="checkbox"
                class="checkbox"
                checked={isCategorySelected(category)}
                onchange={(event) =>
                  toggleCategory(
                    category,
                    event.currentTarget?.checked ?? false
                  )}
              />
              <span class="category-text">
                <strong>{category.categoryName || "Unnamed"}</strong>
                <small class="muted">
                  {category.description || "No description"}
                </small>
              </span>
            </label>
          {/each}
        </div>
      {:else}
        <p class="muted">No categories available yet. Create one above.</p>
      {/if}
    {:else}
      {#if expense.expenseCategories?.length}
        <div class="chip-list">
          {#each expense.expenseCategories as categoryIri}
            <span class="chip">{nameOfCategory(categoryIri) || "Unnamed"}</span>
          {/each}
        </div>
      {:else}
        <p class="muted">No categories linked.</p>
      {/if}
      <small class="helper-text">Enter edit mode to link categories.</small>
    {/if}
  </div>
</article>

// sdk/js/examples/expense-tracker-discrete/src/frontends/vue/ExpenseCard.vue
<!--
Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
All rights reserved.
Licensed under the Apache License, Version 2.0
<LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
at your option. All files in the project carrying such
notice may not be copied, modified, or distributed except
according to those terms.
SPDX-License-Identifier: Apache-2.0 OR MIT
-->
<script setup lang="ts">
import { computed, ref } from "vue";
import type { Expense, ExpenseCategory } from "../../types";

const props = defineProps<{
    expense: Expense;
    availableCategories: ExpenseCategory[];
}>();

const expense = props.expense;
const availableCategories = props.availableCategories;

const isEditing = ref(false);
const paymentStatusLabels: Record<Expense["paymentStatus"], string> = {
    Paid: "Paid",
    Pending: "Pending",
    Overdue: "Overdue",
    Refunded: "Refunded",
};

const paymentStatusEntries = Object.entries(paymentStatusLabels);

const currencyFormatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 2,
});

const purchaseDate = computed(() =>
    expense.dateOfPurchase
        ? new Date(expense.dateOfPurchase).toLocaleDateString()
        : "Date not set"
);

const totalPriceDisplay = computed(() =>
    currencyFormatter.format(expense.totalPrice)
);
const isCategorySelected = (category: ExpenseCategory) =>
    !!expense.expenseCategories?.includes(category["@id"] ?? "");

const toggleCategory = (category: ExpenseCategory, checked: boolean) => {
    const categoryId = category["@id"];
    if (!categoryId) return;

    if (checked) {
        if (!expense.expenseCategories) {
            expense.expenseCategories = [categoryId];
        } else if (!expense.expenseCategories.includes(categoryId)) {
            expense.expenseCategories.push(categoryId);
        }
    } else {
        expense.expenseCategories = (expense.expenseCategories ?? []).filter(
            (value) => value !== categoryId
        );
    }
};

function nameOfCategory(categoryIri: string) {
    return availableCategories.find(
        (c: ExpenseCategory) => c["@id"] === categoryIri
    )?.categoryName;
}
</script>

<template>
    <article class="expense-card">
        <div class="expense-header">
            <div class="header-text">
                <input
                    v-if="isEditing"
                    class="header-input"
                    v-model="expense.title"
                    placeholder="Expense title"
                />
                <h3 v-else class="header-title">
                    {{ expense.title || "New expense" }}
                </h3>
                <p class="muted small-margin">
                    {{ purchaseDate }}
                </p>
            </div>
            <button
                type="button"
                class="icon-btn"
                :aria-label="isEditing ? 'Close editing' : 'Edit expense'"
                @click="isEditing = !isEditing"
            >
                <svg
                    v-if="isEditing"
                    data-slot="icon"
                    fill="none"
                    stroke-width="1.5"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M6 18 18 6M6 6l12 12"
                    ></path>
                </svg>

                <svg
                    v-else
                    data-slot="icon"
                    fill="none"
                    stroke-width="1.5"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125"
                    ></path>
                </svg>
            </button>
        </div>
        <div class="info-grid">
            <div class="field-group">
                <span class="field-label">Description</span>
                <textarea
                    v-if="isEditing"
                    class="textarea"
                    v-model="expense.description"
                    placeholder="Add helpful context"
                ></textarea>
                <p v-else class="value-text">
                    {{ expense.description || "No description yet." }}
                </p>
            </div>
            <div class="field-group">
                <span class="field-label">Total price (€)</span>
                <input
                    v-if="isEditing"
                    type="number"
                    class="input"
                    v-model="expense.totalPrice"
                />
                <span v-else class="value-text">{{ totalPriceDisplay }}</span>
            </div>
            <div class="field-group">
                <span class="field-label">Quantity</span>
                <input
                    v-if="isEditing"
                    type="number"
                    min="1"
                    class="input"
                    v-model="expense.amount"
                />
                <span v-else class="value-text">{{ expense.amount ?? 1 }}</span>
            </div>
            <div class="field-group">
                <span class="field-label">Payment status</span>
                <select
                    v-if="isEditing"
                    class="select"
                    v-model="expense.paymentStatus"
                >
                    <option
                        v-for="[statusIri, label] in paymentStatusEntries"
                        :key="statusIri"
                        :value="statusIri"
                    >
                        {{ label }}
                    </option>
                </select>
                <span v-else class="value-text">
                    {{
                        paymentStatusLabels[expense.paymentStatus] ?? "Unknown"
                    }}
                </span>
            </div>
        </div>
        <div class="field-group">
            <span class="field-label">Categories</span>
            <template v-if="isEditing">
                <div v-if="availableCategories.length" class="category-picker">
                    <label
                        v-for="category in availableCategories"
                        :key="category['@id'] ?? category.categoryName"
                        class="category-option"
                    >
                        <input
                            type="checkbox"
                            class="checkbox"
                            :checked="isCategorySelected(category)"
                            @change="
                                (e) =>
                                    toggleCategory(
                                        category,
                                        (e.target as HTMLInputElement).checked
                                    )
                            "
                        />
                        <span class="category-text">
                            <strong>
                                {{ category.categoryName || "Unnamed" }}
                            </strong>
                            <small class="muted">
                                {{ category.description || "No description" }}
                            </small>
                        </span>
                    </label>
                </div>
                <p v-else class="muted">
                    No categories available yet. Create one in the panel above.
                </p>
            </template>
            <template v-else>
                <div v-if="expense.expenseCategories?.length" class="chip-list">
                    <span
                        v-for="category in expense.expenseCategories"
                        :key="category"
                        class="chip"
                    >
                        {{ nameOfCategory(category) || "Unnamed" }}
                    </span>
                </div>
                <p v-else class="muted">No categories linked.</p>
                <small class="helper-text">
                    Enter edit mode to link categories.
                </small>
            </template>
        </div>
    </article>
</template>
