// sdk/js/examples/test-react-sdk/src/react/ExpenseCategoryCard.tsx
// Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
// All rights reserved.
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
// or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
// SPDX-License-Identifier: Apache-2.0 OR MIT

import { useState } from "react";
import type { ExpenseCategory } from "../shapes/orm/expenseShapes.typings";

export function ExpenseCategoryCard({
    category,
}: {
    category: ExpenseCategory;
}) {
    const [isEditing, setIsEditing] = useState(false);
    const idBase = category["@id"] ?? category.categoryName ?? "category";

    return (
        <article className="category-card">
            <div className="card-header">
                <div>
                    <p className="label-accent">Category</p>
                    <h3 className="title">
                        {category.categoryName || "Untitled category"}
                    </h3>
                </div>
                <button
                    type="button"
                    className="icon-btn"
                    aria-label={isEditing ? "Close editing" : "Edit category"}
                    onClick={() => setIsEditing((prev) => !prev)}
                >
                    {isEditing ? "🗸" : "🖉"}
                </button>
            </div>
            {isEditing ? (
                <div className="edit-grid">
                    <div>
                        <label
                            className="field-label"
                            htmlFor={`${idBase}-name`}
                        >
                            Category name
                        </label>
                        <input
                            id={`${idBase}-name`}
                            className="text-input"
                            value={category.categoryName ?? ""}
                            placeholder="e.g. Groceries"
                            onChange={(e) =>
                                (category.categoryName = e.target.value)
                            }
                        />
                    </div>
                    <div>
                        <label
                            className="field-label"
                            htmlFor={`${idBase}-description`}
                        >
                            Description
                        </label>
                        <textarea
                            id={`${idBase}-description`}
                            className="text-area"
                            value={category.description ?? ""}
                            placeholder="Optional context for this spend bucket"
                            onChange={(e) =>
                                (category.description = e.target.value)
                            }
                        />
                    </div>
                </div>
            ) : (
                <p className="description">
                    {category.description || "No description yet."}
                </p>
            )}
        </article>
    );
}

// sdk/js/examples/expense-tracker/src/frontends/vue/ExpenseCategoryCard.vue
<!--
Copyright (c) 2025 Laurin Weger, Par le Peuple, NextGraph.org developers
All rights reserved.
Licensed under the Apache License, Version 2.0
<LICENSE-APACHE2 or http://www.apache.org/licenses/LICENSE-2.0>
or the MIT license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
at your option. All files in the project carrying such
notice may not be copied, modified, or distributed except
according to those terms.
SPDX-License-Identifier: Apache-2.0 OR MIT
-->
<script setup lang="ts">
import { computed, ref } from "vue";
import type { ExpenseCategory } from "../../shapes/orm/expenseShapes.typings";

const props = defineProps<{
    category: ExpenseCategory;
}>();

const isEditing = ref(false);
const idBase = computed(
    () => props.category["@id"] ?? props.category.categoryName ?? "category"
);

</script>

<template>
    <article class="category-card">
        <div class="card-header">
            <div>
                <p class="label-accent">Category</p>
                <h3 class="title">
                    {{ props.category.categoryName || "Untitled category" }}
                </h3>
            </div>
            <button
                type="button"
                class="icon-btn"
                :aria-label="isEditing ? 'Close editing' : 'Edit category'"
                @click="isEditing = !isEditing"
            >
                {{ isEditing ? "🗸" : "🖉" }}
            </button>
        </div>
        <div v-if="isEditing" class="edit-grid">
            <div>
                <label
                    class="field-label"
                    :for="`${idBase}-name`"
                >
                    Category name
                </label>
                <input
                    :id="`${idBase}-name`"
                    class="text-input"
                    v-model="props.category.categoryName"
                    placeholder="e.g. Groceries"
                />
            </div>
            <div>
                <label
                    class="field-label"
                    :for="`${idBase}-description`"
                >
                    Description
                </label>
                <textarea
                    :id="`${idBase}-description`"
                    class="text-area"
                    v-model="props.category.description"
                    placeholder="Optional context for this spend bucket"
                    
                ></textarea>
            </div>
        </div>
        <p v-else class="description">
            {{ props.category.description || "No description yet." }}
        </p>
    </article>
</template>
