// sdk/js/examples/multi-framework-signals/src/frontends/svelte/HelloWorld.svelte
<script lang="ts">
  import { TestObjectShapeType } from "../../shapes/orm/testShape.shapeTypes";
  import { useShape } from "@ng-org/signals/svelte";
  import flattenObject from "../utils/flattenObject";

  const shapeObject = useShape(TestObjectShapeType);

  function getNestedValue(obj: any, path: string) {
    return path
      .split(".")
      .reduce((cur, k) => (cur == null ? cur : cur[k]), obj);
  }
  function setNestedValue(obj: any, path: string, value: any) {
    const keys = path.split(".");
    let cur = obj;
    for (let i = 0; i < keys.length - 1; i++) {
      cur = cur[keys[i]];
      if (cur == null) return;
    }
    cur[keys[keys.length - 1]] = value;
  }
  const flatEntries = $derived(
    $shapeObject
      ? $shapeObject.entries().map((o) => flattenObject(o)[0] || ({} as any))
      : []
  );
  $effect(() => {
    (window as any).svelteState = $shapeObject;
  });
</script>

{#if $shapeObject}
  <div>
    <p>Rendered in Svelte</p>
    <table border="1" cellpadding="5">
      <thead>
        <tr>
          <th>Key</th>
          <th>Value</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        {#each flatEntries as [key, value] (key)}
          <tr>
            <td style="white-space:nowrap;">{key}</td>
            <td>
              {#if value instanceof Set}
                {Array.from(value).join(", ")}
              {:else if Array.isArray(value)}
                [{value.join(", ")}]
              {:else}
                {JSON.stringify(value)}
              {/if}
            </td>
            <td>
              {#if typeof value === "string"}
                <input
                  type="text"
                  {value}
                  oninput={(e: any) =>
                    setNestedValue($shapeObject, key, e.target.value)}
                />
              {:else if typeof value === "number"}
                <input
                  type="number"
                  {value}
                  oninput={(e: any) =>
                    setNestedValue($shapeObject, key, Number(e.target.value))}
                />
              {:else if typeof value === "boolean"}
                <input
                  type="checkbox"
                  checked={value}
                  onchange={(e: any) =>
                    setNestedValue($shapeObject, key, e.target.checked)}
                />
              {:else if Array.isArray(value)}
                <div style="display:flex; gap:.5rem;">
                  <button
                    onclick={() => {
                      const cur = getNestedValue($shapeObject, key) || [];
                      setNestedValue($shapeObject, key, [
                        ...cur,
                        cur.length + 1,
                      ]);
                    }}>Add</button
                  >
                  <button
                    onclick={() => {
                      const cur = getNestedValue($shapeObject, key) || [];
                      if (cur.length)
                        setNestedValue($shapeObject, key, cur.slice(0, -1));
                    }}>Remove</button
                  >
                </div>
              {:else if value instanceof Set}
                <div style="display:flex; gap:.5rem;">
                  <button
                    onclick={() => {
                      const cur: Set<any> = getNestedValue($shapeObject, key);
                      cur.add(`item${cur.size + 1}`);
                    }}>Add</button
                  >
                  <button
                    onclick={() => {
                      const cur: Set<any> = getNestedValue($shapeObject, key);
                      const last = Array.from(cur).pop();
                      if (last !== undefined) cur.delete(last);
                    }}>Remove</button
                  >
                </div>
              {:else}
                N/A
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{:else}
  <p>Loading state</p>
{/if}

// sdk/js/examples/multi-framework-signals/src/frontends/react/HelloWorld.tsx
import React from "react";
import { useShape } from "@ng-org/signals/react";
import flattenObject from "../utils/flattenObject";
import { TestObjectShapeType } from "../../shapes/orm/testShape.shapeTypes";

export function HelloWorldReact() {
    const state = useShape(TestObjectShapeType)?.entries().next();

    // @ts-expect-error
    window.reactState = state;

    if (!state) return <>Loading state</>;

    // Create a table from the state object: One column for keys, one for values, one with an input to change the value.

    return (
        <div>
            <p>Rendered in React</p>

            <button
                onClick={() => {
                    state.boolValue = !state.boolValue;
                    state.numValue += 2;
                }}
            >
                click me to change multiple props
            </button>

            <table border={1} cellPadding={5}>
                <thead>
                    <tr>
                        <th>Key</th>
                        <th>Value</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    {(() => {
                        const setNestedValue = (
                            obj: any,
                            path: string,
                            value: any
                        ) => {
                            const keys = path.split(".");
                            let current = obj;

                            for (let i = 0; i < keys.length - 1; i++) {
                                current = current[keys[i]];
                            }

                            current[keys[keys.length - 1]] = value;
                        };

                        const getNestedValue = (obj: any, path: string) => {
                            return path
                                .split(".")
                                .reduce((current, key) => current[key], obj);
                        };

                        return flattenObject(state).map(([key, value]) => (
                            <tr key={key}>
                                <td>{key}</td>
                                <td>
                                    {value instanceof Set
                                        ? Array.from(value).join(", ")
                                        : Array.isArray(value)
                                          ? `[${value.join(", ")}]`
                                          : JSON.stringify(value)}
                                </td>
                                <td>
                                    {typeof value === "string" ? (
                                        <input
                                            type="text"
                                            value={value}
                                            onChange={(e) => {
                                                setNestedValue(
                                                    state,
                                                    key,
                                                    e.target.value
                                                );
                                            }}
                                        />
                                    ) : typeof value === "number" ? (
                                        <input
                                            type="number"
                                            value={value}
                                            onChange={(e) => {
                                                setNestedValue(
                                                    state,
                                                    key,
                                                    Number(e.target.value)
                                                );
                                            }}
                                        />
                                    ) : typeof value === "boolean" ? (
                                        <input
                                            type="checkbox"
                                            checked={value}
                                            onChange={(e) => {
                                                setNestedValue(
                                                    state,
                                                    key,
                                                    e.target.checked
                                                );
                                            }}
                                        />
                                    ) : Array.isArray(value) ? (
                                        <div>
                                            <button
                                                onClick={() => {
                                                    const currentArray =
                                                        getNestedValue(
                                                            state,
                                                            key
                                                        );
                                                    setNestedValue(state, key, [
                                                        ...currentArray,
                                                        currentArray.length + 1,
                                                    ]);
                                                }}
                                            >
                                                Add
                                            </button>
                                            <button
                                                onClick={() => {
                                                    const currentArray =
                                                        getNestedValue(
                                                            state,
                                                            key
                                                        );
                                                    if (
                                                        currentArray.length > 0
                                                    ) {
                                                        setNestedValue(
                                                            state,
                                                            key,
                                                            currentArray.slice(
                                                                0,
                                                                -1
                                                            )
                                                        );
                                                    }
                                                }}
                                            >
                                                Remove
                                            </button>
                                        </div>
                                    ) : value instanceof Set ? (
                                        <div>
                                            <button
                                                onClick={() => {
                                                    const currentSet =
                                                        getNestedValue(
                                                            state,
                                                            key
                                                        );
                                                    currentSet.add(
                                                        `item${currentSet.size + 1}`
                                                    );
                                                }}
                                            >
                                                Add
                                            </button>
                                            <button
                                                onClick={() => {
                                                    const currentSet =
                                                        getNestedValue(
                                                            state,
                                                            key
                                                        );
                                                    const lastItem =
                                                        Array.from(
                                                            currentSet
                                                        ).pop();
                                                    if (lastItem) {
                                                        currentSet.delete(
                                                            lastItem
                                                        );
                                                    }
                                                }}
                                            >
                                                Remove
                                            </button>
                                        </div>
                                    ) : (
                                        "N/A"
                                    )}
                                </td>
                            </tr>
                        ));
                    })()}
                </tbody>
            </table>
        </div>
    );
}
